### ISSUE TITLE
Texture error with walls when using optifine

### ISSUE THREAD

**Issue by badcrave** [LeCloutPanda/ConcretePlus-Fabric#2]
Didn't test this without optifine but here's a screenshot of the issue 

![2021-04-06_19 02 58](https://user-images.githubusercontent.com/79771517/113800429-c7f3a500-970b-11eb-9154-036fd9ba0871.png)

**Comment by LeCloutPanda** [comment]
I have been able to replicate the problem and i have found the culprit and I've updated the mod with the fix
