### ISSUE TITLE
Nothing attaches to concrete walls

### ISSUE THREAD

**Issue by gniftygnome** [LeCloutPanda/ConcretePlus-Fabric#3]
Running Minecraft 1.16.5 with the latest Fabric (loader 0.11.3, api 0.32.5), ConcretePlus-Fabric 1.5.4, and no other mods, nothing attaches to concrete walls, including other concrete walls.  I'm guessing you already know about this but since there is no issue filed I might as well file one.

![2021-04-07_11 25 05](https://user-images.githubusercontent.com/50962022/113917017-890a3180-9795-11eb-81f0-266178971f1a.png)
![2021-04-07_11 26 09](https://user-images.githubusercontent.com/50962022/113917021-8a3b5e80-9795-11eb-85ef-1a2a1e94e22e.png)

**Comment by LeCloutPanda** [comment]
I've fixed the issue with it not connecting to any vanilla blocks like it should be and to get the fix just download the latest version.

**Comment by gniftygnome** [comment]
Beautiful; I can confirm 1.5.5 is as expected.  Thanks for the quick fix!
